
var questions = [
  ["Vad gör dig tillfredsställd?", 
  "Skare",
  "Snygga yrkanden och balanskonton på 0", 
  "Korrekt placerade semikolon, vitsiga underrubriker och snygga provtryck från US-AB.",
  "När jag hör mycket engelska talas på vanliga tisdagspubar.", 
  "När saker du förberett länge inte går helt åt skogen", 
  "Jämlikhet", 
  "När omvandlingen till .svg går som den ska.", 
  "När ovvarna kommer i tid", 
  "Spex!", 
  "Att se Konsulatet rent <3", 
  "Smash (bros)! ;)", 
  "När allt funkar som det ska", 
  "Fyra enheter på en tisdag (i enlighet med socialstyrelsens rekommendationer)", 
  "Att klicka ctrl+alt+f och så blir ens kod fin", 
  "När företag bestämmer sig för att ge pengar till oss"],
  ["Vad gör du helst en fredagskväll?", 
  "Skickar kallelse 23:57", 
  "Jag är för gammal för sektionsarbete, så ingenting antar jag?", 
  "Genomför ett test av någonting gott/roligt.", 
  "Går på fkm*s fredagspub.",
  "Lagar sjukt mycket mat", 
  "Kolla en informerande dokumentär", 
  "Collage med fina bilder.", 
  "Kommunicerar", 
  "Tittar igenom alla gamla spex från -82 till -23", 
  "Diskar!", 
  "Spelar volleyboll! Eller kanske Mariokart...? Klättring är ju också skoj... eller.. fan, jag kan inte bestämma mig, får nog göra allting!", 
  "Chillar och käkar pizza efter att jag blivit klar med mina inlämningar.", 
  "Studiebesök på Hardox!", 
  "Planerar en kryptografisk skattjakt åt kommande generationer", 
  "Stirrar på verifikat i fortnox"],
  ["Vilka vill du bossa över?", 
  "Allt och alla", 
  "Styrelsen", 
  "Sektionens vassaste pennor.", 
  "Sektionsaktiva som gärna vill arrangera egna event å min nämnds vägnar.", 
  "En mindre grupp på 400 personer", 
  "Alla och ingen på samma gång", 
  "Alla FArtdårar.", 
  "Kommunikatörer", 
  "En stor grupp full med massor av kreativa och talangfulla människor", 
  "Alla i Kons.", 
  "Helst minionerna, men nØllan duger.", 
  "Mina föreläsare såklart", 
  "Tilltåndsenheten och kommunen", 
  "Hyperkompetenta supernördar", 
  "De som behöver lite vind i seglet"],
  ["Jobbar du helst på egen hand eller i grupp? (1=på egen hand, 5=i grupp)", 4, 2, 3, 3, 5, 5, 3, 3, 4, 3, 4, 4, 5, 3, 4],
  ["Hur mycket tid vill du lägga på sektionssaker? (1=lite grann, 5=jättemycket)", 3, 2, 2, 3, 5, 2, 2, 4, 4, 2, 3, 3, 5, 5, 4],
  ["Vilka av följande citat stämmer bäst på dig?", 
  '"Absolute power corrupts absolutely"', 
  '"Gör det rätt, eller gör det igen"', 
  '"Låt oss nu stanna upp ett ögonblick och ställa oss några frågor…"', 
  '"Mr. Worldwide" - Pitbull', 
  '"Jag ska inte ljuga, det är alltid kul att ha en personkult efter sig"', 
  '" Vad funkar bäst, teamwork!"', 
  '"En bild säger mer än tusen ord"', 
  '"Man måste tänka sig Sisyfos lycklig"', 
  '”Vem är det som stör egentligen?”', 
  '"Aldrig bitter."', 
  '"Rör på dig nu, så kan du äta mer sen."', 
  '"Kom igen, det blir kul!"', 
  '"Hellre sömnbrist än trist!"', 
  '"Har du prövat att starta om den?"', 
  '"Välsignad du står framgång du når"'],
  ["Vilka av följande situationer ser du dig helst i?",
   'På gränsen', 
   "Bokföring på middagsdejt med min revisorspartner", 
   "Sittande på en skrivarstuga författande ännu en artikel till nästa tidningsnummer tillsammans med mina medskribenter.", 
   "Min nämnd håller i många events, och många kommer på de eventsen.", 
   "Du demonstrerar en sjukt bra dans till en bangerlåt framför 200 personer ", 
   "Prideparaden", 
   "Photoshoppad i Bahamas.", 
   "Här och nu", 
   "På eller bakom scen", 
   "I konsbadkaret.", 
   "Att prova på nya saker med gott umgänge!", 
   "En hel helg utan några inlämningar", 
   "Du står bakom baren och ser folkhavet skriksjunga texten till shoreline klockan 02:00 en lördag!", 
   "Hopkrupen i en boll under ett skrivbord med en badanka på huvudet, laptop i knät och 127 personer som väntar på att digitala sångboken ska funka igen", 
   "På lunchföreläsning i V2, där företaget i fråga bjuder på sushi. Jag har inget schemalagt på hela eftermiddagen och kan spendera tiden nätverkandes med företagsrepresentanterna."],
  ["Vad skulle du vilja bidra till på Fysiksektionen?", 
  "Hybris", 
  "Stadgestöd och erfarenhet", 
  "Ett fantastiskt stycke underhållning någon gång per termin.", 
  "Att internationella studenter ska bättre kunna ta del av sektionslivet.", 
  "En episk period för alla inblandade", 
  "Mer jämlikhet. Och fika", 
  "Göra Fysiksektionen lite snyggare ;)", 
  "Sammanhållning", 
  "Dra i ett stort projekt som bidrar med massor av glädje", 
  "Att göra kons jättemysigt.", 
  "Sprida glädje och roligheter för den gemene f-teknologen.", 
  "En schysst utbildning för alla F-teknologer", 
  "Ge möjlighet att ha kul och slappna av efter allt plugg!", 
  "Digital icke-misär", 
  "Öka/förbättra varumärket att vara en matematiker/fysiker"],
  ["Vilka tidsintervall är du vaken på?", 
  "17:23 - 23:00, 6x per år", 
  "10-15 (med lunchpaus 12-13.30)", 
  "Helst mellan kl8 och kl24.", 
  "07-23 eller 10-03 (GMT +1)", 
  "På våren: 8-23, på sommaren 06-03, på hösten: 14-21.", 
  "Sover mest", 
  "17:23-17:58 + lite till efter fikapausen", 
  "10:00 - 02:00", 
  "12.00-0.00", 
  "De vanliga.", 
  "07-23", 
  "Beror lite på hur schemat ser ut för dagen, men jag är oftast någorlunda utvilad när jag vaknar i alla fall", 
  "17:23-05:00", 
  "11:42-03:46", 
  "05-22"],
  ["Om Fysiksektionen fick en miljon kronor till, vad skulle du vilja göra med dem?", 
  "Bahamas", 
  'Kolla bokföringen, skatteregler och säkerställ att pengarna är lagliga', 
  "Tvinga Osqledaren på knä.", 
  "Betala professionella översättare att översätta allt material som inte finns på engelska.", 
  "Mer mat", 
  "Köpa en fet prideflagga och massa fika.", 
  "Se till att F-teknologerna får KTH:s fetaste märkeskläder.", 
  "Köpa en megafon i rent guld", 
  "Köpa en teater (man kan alltid drömma)", 
  "Bygga ut kons.", 
  "Skicka hela sektionen på skidresa till alperna!", 
  "Köpa en massa pizza till alla F-teknologer (vem gillar inte pizza?)", 
  "Boka hela Alba Nova tre dagar i sträck, ha olika dansgolv i varje övningssal och låta The Killers spela i FR4!", 
  "Bygga en bartender AI robot att ersätta hela fkm* med", 
  "Alltid öppen bar på FNs event"],
  ["En ska vara...", 
  "singel! eh, jag menar... tillgänglig!?", 
  "gammal", 
  "Kreativ", 
  "Worldwide.", 
  "alltid redo", 
  "Snäll", 
  "... tacksam för jpg-filer med genomskinlig bakgrund", 
  "tydlig", 
  "Spexig", 
  "ren.", 
  "Aktiv!", 
  "Snäll och omtänksam:)", 
  "ansvarsfull på nubbedraget nån gång i mars", 
  "fikasugen.", 
  "nogrann."],
  ["Jag skulle inte klara mig utan...", 
  "gratis mat på SM!", 
  "yttrande- och förslagsrätt", 
  "Google docs/microsoft word.", 
  "En som jag kan jobba tillsammans med.", 
  "alla härliga F-teknologer <3", 
  "Fika",
  "Inkscape (helst inte på grekiska).", 
  "dig", 
  "Punsch och stor fikabudget", 
  "Magic Erasers.", 
  "att röra på mig.", 
  "Alla kursnämnder och trädkramare", 
  "Nespressomaskinen <3", 
  "badankor", 
  "min laptop"],
  ["Det här vill jag få ut av mitt engagemang:", 
  "En överblick av sektionen (+ lite maktlystenhet)", 
  "Hänga kvar i sektionen *lite* till", 
  "Skoj och erfarenhet av att sätta samman en tidning grafiskt och innehållsmässigt.", 
  "Erfarenhet av att arrangera evenemang och vara en ledare, och att få kontakter med internationella studenter.", 
  "Odödlighet", 
  "Gemenskap", 
  "En nice grafisk profil och att få träffa andra designälskare.", 
  "En nöjd sektion", 
  "Dra i projekt och jobba med roliga människor", 
  "Ha det riktigt gött med resten av nämnden!", 
  "Känslan av att bidra till det allmänna välmåendet på sektionen.", 
  "En bättre utbildning! (och ett regnbågsfärgat lövmärke)", 
  "Lära känna massor nya, spännande personer samt få hänga och fixa event tillsammans med ett fantastiskt gäng!", 
  "Färdigheter för livet!", 
  "Ha det kul och få andra att bli en del av sektionen också"],
  ];
  
var namnder = ["Sektionsstyrelsen (Styret)", "Revisorerna", "Sektionstidningen (The Force)", "Internationella nämnden (FINT)", "Mottagningen", "Jämlikhetsnämnden (JämN)", "Designnämnden (FArt)", "Kommunikationsnämnden (FCom) centralt", "Spexet (Fysikalen)", "Fysikrumskommitén (FRum)", "Aktivitetsnämnden (FAN)", "Studienämnden (FSN)", "Klubbmästeriet (fkm*)", "Utvecklingsgruppen (F.dev)", "Näringslivsnämnden (FN)"]

